# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gmolin <gmolin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/15 14:48:14 by gmolin            #+#    #+#              #
#    Updated: 2019/10/16 16:26:59 by gmolin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

PROGRAMS = ft_display_file.c

all: $(NAME)

$(NAME):
		gcc -o $(NAME) -Wall -Wextra -Werror $(PROGRAMS)

clean:

fclean:
		/bin/rm -f $(NAME)

re: fclean all
